name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  mw35:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: make build
      - run: make container
      - run: bash test.sh